spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://81.68.217.102:3306/usercenter
    url: jdbc:mysql://localhost:3306/usercenter
    username: root
#    password: Jakie666
    password: root
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api

